In [2]:
# Kellen Hartnett
# Adrian Lewis
# Connor Lowe
# Sahibjeet Singh
# Garrett Tashiro
# EE 475, Group 5 Capstone Project
# Interpolates points given corners of a chessboard

import numpy as np

# array length function
def array_length(a):
    counter = 0
    for char in a:
        counter += 1
    return counter

# setting up interpolation between 4 corner points
h1 = [60, 169]
a1 = [57, 455]
h8 = [345, 166]
a8 = [341, 453]
board = np.zeros((8, 8, 2))
board2 = np.zeros((8, 8, 2))
board3 = np.zeros((8, 8, 2))
board[0][0]  = h1
board[0][7]  = a1
board[7][0] = h8
board[7][7] = a8

# Horizontal interpolation
for i in range(0, 8):
    for j in range (1, 7):
        board[i][j][0] = (board[i][0][0] * ((7-j)/7)) + (board[i][7][0] * (j/7)) 
        board[i][j][1] = (board[i][0][1] * ((7-j)/7)) + (board[i][7][1] * (j/7))

# Vertical interpolation
for i in range(0, 8):
    for j in range(0, 8):
        board2[i][j][0] = (board[0][i][0] * ((7-j)/7)) + (board[7][i][0] * (j/7)) 
        board2[i][j][1] = (board[0][i][1] * ((7-j)/7)) + (board[7][i][1] * (j/7))
        
# rotation
for i in range(0, 8):
    for j in range(0, 8):
        board3[i][j] = board2[j][i]
                
# Printing 
np.set_printoptions(threshold=np.inf)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print("chessboard = \n", board2)
print("chessboard2 = \n", board3)

# setting up interpolation between 4 corner points
p1 = [39, 87]
p8 = [324, 86]
r1 = [40, 46]
r2 = [325, 45.5]
q2 = [365, 66]
captured = np.zeros((8, 2, 2))
captured2 = np.zeros((8, 2, 2))
captured[0][0] = p1
captured[7][0] = p8
captured[0][1] = r1
captured[7][1] = r2

# Vertical interpolation
for i in range(1, 7):
    for j in range(0, 2):
        captured[i][j][0] = (captured[0][j][0] * ((7-i)/7)) + (captured[7][j][0] * (i/7)) 
        captured[i][j][1] = (captured[0][j][1] * ((7-i)/7)) + (captured[7][j][1] * (i/7))
                     
# Printing 
np.set_printoptions(threshold=np.inf)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print("\ncaptured = \n", captured)
print("\nq2 = \n", q2)

# white capture pieces indices need to be 64-80
white = [[39, 87], [79.714, 86.857], [120.429, 86.714], [161.143, 85.571], [201.857, 86.429],
         [242.571, 86.143], [324, 86], [40, 46], [80.714, 45.929], [121.429, 45.857], 
         [162.143, 45.786], [202.857, 45.714], [284.286, 45.571], [325, 45.5], [365, 66]]

# black captured pieces indices need to be 81-97
black = [[35, 534], [75.429, 534.357], [115.857, 534.214], [156.286, 534.071], [196.714, 533.929], 
         [237.143, 533.786], [277.571, 533.643], [318, 533.5], [36, 575.5], [76.357, 575.357], 
         [116.714, 575.214], [157.071, 575.071], [197.429, 574.929], [237.786, 574.786], 
         [278.143, 574.643], [318.5, 574.5], [358.5, 554]]

print("white capture pieces indices need to be 64-80")
print("\nwhite captured = \n", white)
print("black captured pieces indices need to be 81-97")
print("\nblack captured = \n", black)

chessboard = 
 [[[60.000 169.000]
  [100.714 168.571]
  [141.429 168.143]
  [182.143 167.714]
  [222.857 167.286]
  [263.571 166.857]
  [304.286 166.429]
  [345.000 166.000]]

 [[59.571 209.857]
  [100.265 209.449]
  [140.959 209.041]
  [181.653 208.633]
  [222.347 208.224]
  [263.041 207.816]
  [303.735 207.408]
  [344.429 207.000]]

 [[59.143 250.714]
  [99.816 250.327]
  [140.490 249.939]
  [181.163 249.551]
  [221.837 249.163]
  [262.510 248.776]
  [303.184 248.388]
  [343.857 248.000]]

 [[58.714 291.571]
  [99.367 291.204]
  [140.020 290.837]
  [180.673 290.469]
  [221.327 290.102]
  [261.980 289.735]
  [302.633 289.367]
  [343.286 289.000]]

 [[58.286 332.429]
  [98.918 332.082]
  [139.551 331.735]
  [180.184 331.388]
  [220.816 331.041]
  [261.449 330.694]
  [302.082 330.347]
  [342.714 330.000]]

 [[57.857 373.286]
  [98.469 372.959]
  [139.082 372.633]
  [179.694 372.306]
  [220.306 371.980]
  [260.918 371.653]
  [301.531 371.327]
  [342.143 371.000]]

 [[57.429 414.143]
  [9